### PR TITLE
Fix the conversion from filetime to ns

### PR DESCRIPTION
**Pull request by LorenVS**
I might be wrong, but the current code does not seem to line up with the comment on filetimes. Hopefully this is the correct fix

### CODE REVIEW

**Comment by LorenVS** [comment]
Turns out my initial guess here was wrong. The code is actually functioning correctly, but the naming of many of the variables is suspect. By dividing by 10 (the original code), a conversion was being done from 100ns buckets to microseconds, not back to nanoseconds. A number of variables that were named ns_ were actually storing quantities in microseconds.

This PR no longer affects functionality, but solves some naming issues with these variables

**Comment by LorenVS** [comment]
This begs the question, since Timespec uses nanosecond precision, whether throwing out the 100ns precision is correct.

**Comment by alexcrichton** [comment]
Aha! I looked into this a bit as well and I thought the number of 0s on the end of that constant looked suspicious... Thanks for this!

**Comment by alexcrichton** [comment]
I'd also be fine actually using the ns precision if possible :)

**Pull request merged**
